services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/backups:/docker-entrypoint-initdb.d/backups
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - db

  python:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - kafka
      - db
    volumes:
      - ./:/app 

volumes:
  pgdata:

